version: '3.3'
services:
        adguardhome:
                image: adguard/adguardhome
                container_name: adguardhome
                restart: unless-stopped
                volumes:
                        - {your/path/to/workdir}:/opt/adguardhome/work
                        - {your/path/to/confdir}:/opt/adguardhome/conf
                ports:
                        - 53:53/tcp
                        - 53:53/udp
                        - 443:443/tcp
                        - 80:80/tcp
                        - 443:443/udp
                        - 3000:3000/tcp
                networks: # network only required to setup if not using default bridge network
                        mynetwork:
                                ipv4_address: {assign_ip_address_manually}
networks:
        mynetwork:
                external: true
